services:
  brc_site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brc_site
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brc_reverb
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8082:8080"
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"